name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest # macOS is required for iOS builds

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Flutter)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Specify your desired Flutter version
          channel: 'stable'

      # Install dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Create a basic Podfile if none exists
      - name: Create Podfile 
        run: pod init

      # Install CocoaPods dependencies (for iOS)
      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod install --repo-update

      # Build iOS app
      - name: Build iOS
        working-directory: ios
        run: |
          flutter build ios --release --no-codesign

      # Optional: Archive the build output
      - name: Archive iOS build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/*.app
