name: Flutter Build

on:
  push:
    tags:
      - '*'

env:
  FLUTTER_VERSION: "3.29.2"  # Explicit stable version

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.setup-flutter.outputs.flutter-version }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        id: setup-flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          architecture: x64

  build_web:
    name: Build Web
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web
      
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build_windows:
    name: Build Windows
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  build_linux:
    name: Build Linux
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - run: flutter config --enable-linux-desktop
      - run: flutter create --platforms=linux .
      - run: flutter pub get
      - run: flutter build linux --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

  build_android:
    name: Build Android
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk       
            
  create_release:
    name: Create Release
    needs: [setup, build_android, build_windows, build_linux, build_web]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
        
      - name: Create zip archives
        run: |
          cd artifacts
          zip -r windows-build.zip windows-build/
          zip -r linux-build.zip linux-build/
          zip -r web-build.zip web-build/
          cd ..
          
      - name: Calculate SHA-256 checksums
        id: sha
        run: |
          # Calculate checksums for all files
          checksums=$(sha256sum artifacts/android-apk/app-release.apk \
                    artifacts/windows-build.zip \
                    artifacts/linux-build.zip \
                    artifacts/web-build.zip)
          # Escape newlines for output
          checksums="${checksums//'%'/'%25'}"
          checksums="${checksums//$'\n'/'%0A'}"
          checksums="${checksums//$'\r'/'%0D'}"
          echo "checksums=${checksums}" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ needs.setup.outputs.version }}
          tag_name: v${{ needs.setup.outputs.version }}
          draft: false
          prerelease: false
          files: |
            artifacts/android-apk/app-release.apk
            artifacts/windows-build.zip
            artifacts/linux-build.zip
            artifacts/web-build.zip
          body: |
            ## Release ${{ needs.setup.outputs.version }}
            
            ### Downloads
            - [Android APK](app-release.apk)
            - [Windows Build](windows-build.zip)
            - [Linux Build](linux-build.zip)
            - [Web Build](web-build.zip)
            
            ### SHA-256 Checksums
            ```
            ${{ steps.sha.outputs.checksums }}
            ```          