name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter build web
      
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter build linux
      
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - run: flutter pub get
      
      - run: flutter build apk --release
      # For app bundle: flutter build appbundle --release
      
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: |
          flutter build ios --release --no-codesign
          cd ios
          pod install
      
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/Release-iphoneos/
